//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdOTP.Locale {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rdOTP.Locale.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   OTP not configured. Click &apos;submit&apos; and setting it first!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_NotConfigured {
            get {
                return ResourceManager.GetString("Auth_NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dialog will be closed in {0} seconds.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Auth_Timeout {
            get {
                return ResourceManager.GetString("Auth_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A required module(&apos;{0}&apos;) is missing.
        ///Please reinstall this program.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_moduleNotFound {
            get {
                return ResourceManager.GetString("Error_moduleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This program only support Windows 8(Windows Server 2012) or higher.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Error_osrequired {
            get {
                return ResourceManager.GetString("Error_osrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you change secret key, You need change all OTP information at your phone.
        ///Continue?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KeySettings_changeconfirm {
            get {
                return ResourceManager.GetString("KeySettings_changeconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key generation complete!.
        ///Please run &apos;OTP Test&apos; first.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KeySettings_complete {
            get {
                return ResourceManager.GetString("KeySettings_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export secret key to file (Encoding : UTF8)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KeySettings_ExportDialogTitle {
            get {
                return ResourceManager.GetString("KeySettings_ExportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot export key at file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KeySettings_ExportFailed {
            get {
                return ResourceManager.GetString("KeySettings_ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key has been exported.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KeySettings_ExportSuccess {
            get {
                return ResourceManager.GetString("KeySettings_ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you import secret key, You need change all OTP information at your phone.
        ///Continue?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KeySettings_importConfirm {
            get {
                return ResourceManager.GetString("KeySettings_importConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import secret key from file (Encoding : UTF8)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KeySettings_ImportDialogTitle {
            get {
                return ResourceManager.GetString("KeySettings_ImportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Key File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KeySettings_ImportInvalidKey {
            get {
                return ResourceManager.GetString("KeySettings_ImportInvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read key file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KeySettings_ImportReadFailed {
            get {
                return ResourceManager.GetString("KeySettings_ImportReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key has been imported.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KeySettings_ImportSuccess {
            get {
                return ResourceManager.GetString("KeySettings_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Key does not exist.
        ///Generate key or import saved key first과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KeySettings_keynotfound {
            get {
                return ResourceManager.GetString("KeySettings_keynotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test Failed!
        ///Try again or re-register QR Code at your phone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KeySettings_testFailed {
            get {
                return ResourceManager.GetString("KeySettings_testFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test Success!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KeySettings_testPassed {
            get {
                return ResourceManager.GetString("KeySettings_testPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_Installed {
            get {
                return ResourceManager.GetString("Main_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not installed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_NotInstalled {
            get {
                return ResourceManager.GetString("Main_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main_Version {
            get {
                return ResourceManager.GetString("Main_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Service_Installed {
            get {
                return ResourceManager.GetString("Service_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Installed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Service_NotInstalled {
            get {
                return ResourceManager.GetString("Service_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopped과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Service_Notrunning {
            get {
                return ResourceManager.GetString("Service_Notrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Service_runnning {
            get {
                return ResourceManager.GetString("Service_runnning", resourceCulture);
            }
        }
    }
}
